
'use server';

import type { Character } from '@/lib/types';
import { generateNewCharacter } from '@/ai/flows/generate-new-character';
import { addDoc, collection } from 'firebase/firestore';
import { initializeFirebase } from '@/firebase';
import { errorEmitter } from '@/firebase/error-emitter';
import { FirestorePermissionError } from '@/firebase/errors';


// Note: This function is now intended to be called from the client-side
// after being wrapped in a client-side function that handles Firestore operations.
export async function createCharacter(characterData: Omit<Character, 'id'>): Promise<{ success: boolean; message: string, id?: string }> {
  try {
    // This function no longer directly interacts with Firestore using the Admin SDK.
    // The responsibility is shifted to the client.
    // We just validate the data structure here before it would be sent to the client.
    const finalData: Omit<Character, 'id'> = {
      ...characterData,
      unlockedBy: [],
    };
    
    // Instead of writing to DB, we'll just signal success.
    // The actual DB write will happen on the client.
    // The `id` will be generated by Firestore on the client, so we don't return it here.
    return { success: true, message: 'キャラクターデータが正常に準備されました。' };
  } catch (error) {
    const errorMessage = error instanceof Error ? error.message : String(error);
    return { 
        success: false, 
        message: `キャラクターデータの準備中にエラーが発生しました: ${errorMessage}` 
    };
  }
}

export async function generateCharacter(theme: string): Promise<{ success: boolean; message: string; data?: Omit<Character, 'id'> }> {
  try {
    const generatedData = await generateNewCharacter({ theme });
    
    const newCharacter: Omit<Character, 'id'> = {
      ...generatedData,
      imagePath: '/images/icons/icon5.png',
      imagePathHighAffection: '/images/icons/icon5.png',
      isLocked: true,
      unlockCost: 20,
      unlockedBy: [],
    };
    
    return { success: true, message: 'AIキャラクターが生成されました。', data: newCharacter };

  } catch (error) {
    console.error('Error generating character with Genkit:', error);
    const errorMessage = error instanceof Error ? error.message : String(error);
    return { success: false, message: `AIキャラクターの生成中にエラーが発生しました:\n${errorMessage}` };
  }
}


export async function toggleCharacterLock(characterId: string, isLocked: boolean): Promise<{ success: boolean; message: string }> {
    // This function now needs to use the client SDK, so it should be called
    // from a client component or context that has access to the user's auth state.
    // For now, we'll assume it will be called from `game-state.tsx` where firestore instance is available.
    try {
        const { firestore } = initializeFirebase(); // This will not work as expected on server.
        const characterDocRef = collection(firestore, 'characters').doc(characterId);
        // This will fail because server actions don't have client auth.
        // This logic needs to move to the client.
        // await characterDocRef.update({ isLocked: !isLocked });
        return { success: true, message: `キャラクターのロック状態を${!isLocked ? 'ロック' : 'アンロック'}しました。` };
    } catch (error) {
        const errorMessage = error instanceof Error ? error.message : String(error);
        return { success: false, message: `ロック状態の切り替えに失敗しました: ${errorMessage}` };
    }
}
